spring:
  application:
    name: eureka-server
  profiles:
    active: dev

server:
  port: 1111

eureka:
  instance:
    hostname: localhost
  client:
#   由于该应用为注册中心，所以设置为 false, 代表不向注册中心注册自己。
    register-with-eureka: false
#   由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为 false。
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
